<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Email\EmailTemplates\en\verifyemail.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="Refit" Version="9.0.2" />
    <PackageReference Include="Refit.HttpClientFactory" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email\EmailTemplates\en\verifyemail.html" />
  </ItemGroup>

</Project>
